### ISSUE TITLE
Unused files - "hosts" and "hostname" can be removed from project

### ISSUE THREAD

**Issue by heliusblackstar** [DrCool2/Agent#1]
I noticed these two files "hosts" and "hostname" were introduced in a recent commit, (https://github.com/DrCool2/Agent/commit/c04457fb55b5e36ac913b7344b1a8f672b4de31d ) however they are not referenced by agent.sh and can be removed from the project.

If you have a need to do text-injection into a system file, I'd recommend using the BASH heredoc feature.  I use them all the time and they are awesome.

**Comment by DrCool2** [comment]
Please confirm that those files are now removed.
Thanks,
DrCool2

**Comment by heliusblackstar** [comment]
Yep, they are gone from master now.
